### ISSUE TITLE
Decide whether to keep or ditch the Data URI

### ISSUE THREAD

**Issue by waldyrious** [browserpad/browserpad#2]
**why remain an "app-in-url"**:

1. when saved as a bookmarklet, the app works even if the site (or even the whole Internet) is down
    - then again, the site likely won't be down often since github has pretty high uptime stats,
       and if the whole internet is down, well, who would use a browser notepad anyway?
    - you can save the html file to your disk and have a local copy that works regardless
       (note: this is an argument for not splitting the script & css to a separate file;
       <s>the ico file should likewise be included as a data URI in the html</s> <-- done in 093c4bf)
2. the readability and length limitations of a data URI / browser URL bars / a href attributes
   may force the code to remain short and concise.
   - on the other hand, that's pretty much a hack;
     it would be much nicer to have properly indented, documented and linted code.
3. instant loading (no network request). Note that this only works
   if the data URI link has been saved as a bookmarklet, otherwise the loading is instant alright,
   but only *after* the host page has been loaded, which defeats the purpose.

**why abandon the data URI approach and become a regular web page**:

1. having the app in the url bar was cute/clever when it started out (d71b37b)<br/>
   as "`data:text/html,<textarea%20autofocus/>`",
   but now it's not practical to either write or read that anymore
2. if saved as a bookmarklet, updates (bug fixes or new functionality)
   don't become available unless the bookmark is manually updated/replaced
3. having the whole app within a string in a `href` attribuite of a link is ugly, hard to maintain,
   and requires extra encoding that wouldn't be necessary otherwise
4. this doesn't matter much, but if we want to be pedantic, github (and any other code analysis tool)
   will report accurate stats for languages used in the project
5. usability/convenience: going to browserpad.org would drop anyone directly into the text editor!
   (this would require a proper "about" dialog though)

**Comment by waldyrious** [comment]
Seems pretty clear that abandoning the Data URI is the way to go, but I'll let this sit for a while and maybe others can add more arguments or counterpoint the existing ones.

**Comment by eduardomps** [comment]
why not both? defaults obviously to site, but offer "use as a bookmarklet". it would need a comment section right at start (Browserpad Bookmarklet version X.Y.Z)

**Comment by waldyrious** [comment]
Good point @eduardomps. Even better if the bookmarklet is generated dynamically so its code doesn't have to be manually kept in sync with the unwrapped one :D
