### ISSUE TITLE
Ensure that CSS styling isn't preserved when pasting text

### ISSUE THREAD

**Issue by waldyrious** [browserpad/browserpad#42]
This shouldn't happen in a textarea, but I just experienced it when copying the bottom 4 paragraphs of https://www.keybits.net/post/import-keybase-private-key/ into browserpad (Firefox v50 on OS X Yosemite 10.10.5).

The solution may be something like this: http://stackoverflow.com/a/12028136/266309

**Comment by SenadAlagic** [comment]
I completed this task! This might sound weird but I don't know what to do. Do I fork the repo again and commit changes there and then do the PR or..? For some reason I can't do "git pull". Help?

**Comment by waldyrious** [comment]
Thanks for taking this on, @SenadAlagic! About your questions, I think you resolved them by merging the changes back into your fork, but let me know if this helps clarify:

When I merged your last PR, I squashed the commits into a single one (since the last two were just adjustments to the original commit, rather than separate functionality). This means that the branch `gh-pages` in your fork diverged from the equivalent branch in this repository. This was the status of things immediately after I merged your PR:

```
* ← SenadAlagic:gh-pages
|
*
|
*
|
*   * ← browserpad:gh-pages (squashed commit with the changes from your PR) 
 \ /
  * ← latest commit in browserpad:gh-pages prior to your PR
  |
  ⋮
```

This means that git wouldn't allow you to simply pull from `browserpad:gh-pages` to `SenadAlagic:gh-pages`, as that would make you lose the three commits in your copy of the branch. Of course, the _contents_ of those commits are the same as the squashed commit from this repo, but git doesn't detect that, so it tries to prevent you from losing work.

One solution is as you did, to merge the changes back into your branch, with a merge commit. That creates a graph similar to this:

```
  * ← SenadAlagic:gh-pages (merge commit)
 / \
*   | 
|   |
*   |
|   |
*   |
|   |
*   * ← browserpad:gh-pages (squashed commit with the changes from your PR) 
 \ /
  * ← latest commit in browserpad:gh-pages prior to your PR
  |
  ⋮
```

But the cleanest approach, since you know that your local changes were already included in the upstream (browserpad's) `gh-pages`, would be to tell git to (re)set your branch so it points to the same commit as the upstream branch:

    git reset --hard UPSTREAM_NAME/gh-pages

...where UPSTREAM_NAME is the local name of the browserpad upstream in your local clone of the repository; you can check that name by doing `git remote -v`.

That would result in a synced git graph, like this:

```
* ← browserpad:gh-pages / SenadAlagic:gh-pages
|
* ← latest commit in browserpad:gh-pages prior to your PR
|
⋮
```

Then you could add new commits to `gh-pages` and submit PRs from there normally.

**Comment by SenadAlagic** [comment]
Will definitely save what you said for later. I don't quite _fully_ understand  but I will look into it. Thank you for your help.

**Comment by waldyrious** [comment]
I don't think anyone ever fully understands git :laughing: but feel free to ask further clarifying questions. I will hide the comments as off-topic (as they don't address this issue's main subject), but they will remain here for reference.

**Comment by SenadAlagic** [comment]
Again, sorry to ask. Should this issue be closed?

**Comment by waldyrious** [comment]
Yeah, as we discussed in PR #56, this issue is no longer reproducible. I'll close it, but in case anyone bumps into it in the future, we can reopen it and fix it with the code from that PR. Thanks for looking into this!
