### ISSUE TITLE
Saving the document saves an empty file

### ISSUE THREAD

**Issue by SenadAlagic** [browserpad/browserpad#61]
While doing Ctrl+S or even clicking the "save" button the file is downloaded but it's empty. I'm pretty sure it worked before somehow.

**Comment by angezid** [comment]
There are two `textarea` elements. The code `this.href = URL.createObjectURL(new Blob([document.querySelector('textarea').value] , {type:'text/plain'}));` select first, which not contains any text. Just add `id` to the `document.querySelector('textarea#textbox').value` to fix this.

**Comment by SenadAlagic** [comment]
Thank you for your input, I've already looked into this and the PR is ready.

**Comment by waldyrious** [comment]
Fixed with #62. Thanks @SenadAlagic, @angezid and @DasWordNerd for identifying the issue and fixing it, and apologies for taking so long to address it. Hopefully this was a one-off and future contributions will be integrated more swiftly! :)
