### ISSUE TITLE
Replace deprecated `event.keyCode` property

### ISSUE THREAD

**Issue by waldyrious** [browserpad/browserpad#67]
[`KeyboardEvent.keyCode`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) is deprecated. The code that relies on this should be migrated to the recommended approaches in that page, in particular the [`.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) and/or [`.code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) properties.

**Comment by SenadAlagic** [comment]
Hello again @waldyrious . Since you are absent for a while I thought I should check in a bit. I hope everything is alright.

**Comment by waldyrious** [comment]
Thanks for asking. All is OK, but I've been busier than usual lately, so my GitHub activity has been limited and I've purposely avoided engaging with conversations in projects like this that I want to give my full attention to. I'll come back to regular activity once my activity elsewhere normalizes.

**Comment by SenadAlagic** [comment]
Ah I understand. No worries!

**Comment by SenadAlagic** [comment]
No problem! One issue at a time 😄
