### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by waldyrious** [browserpad/browserpad#8]
- Ctrl-S = save, Ctrl+O = open -- see [here](https://github.com/itsapi/notepad/blob/master/src/js/listeners.js#L63-L75)

Note: I had bookmarked a link somewhere about not overriding browser shortcuts, but can't find it at the moment.

**Comment by SenadAlagic** [comment]
Should I do some more work or is this issue supposed to be closed?

**Comment by waldyrious** [comment]
Yeah, with the merge of #51, it makes sense to close this. Thanks for the heads-up!
