### ISSUE TITLE
Print icon

### ISSUE THREAD

**Issue by waldyrious** [browserpad/browserpad#9]
See [here](https://github.com/itsapi/notepad/blob/master/src/js/listeners.js#L26-L28)

**Comment by SenadAlagic** [comment]
If I'm not mistaken I added this functionality some time back. Should this issue be closed?

**Comment by SenadAlagic** [comment]
I have to correct myself here, I did not add the icon I added the functionality and the word "print" as text. Should I still add the icon?

**Comment by waldyrious** [comment]
Oh! Good point, I didn't recall this issue when you submitted #51. In my defense, your PR came almost exactly 7 years after I opened this issue, so it's natural that it wasn't exactly front of mind 😅

I don't think we need a print icon specifically (maybe we could use an emoji, 🖨️, but IMO the plain word works well enough.) I'll close this as resolved by #51 :)

**Comment by SenadAlagic** [comment]
No need for any apologies, I understand everything. I aplogize if I ever confuse you or cause any issues. Thank you for allowing me to learn and work with you! Print emoji would be good too, but as you say, the plain work works well enough. Enjoy!
